name: excited
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_core: ^0.4.0+3
  firebase_auth: ^0.11.1+5
  google_sign_in: ^4.0.2
  curved_navigation_bar: ^0.1.2 #latest version
  fluro: ^1.4.0
  flutter_facebook_login: ^2.0.1


  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.4.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/EXCITED_R.png
      - assets/images/EXCITED_R_BCO.png
      - assets/images/loginimage.jpg
      - assets/images/flag.jpg
      - assets/images/login2.jpg
      - assets/images/1.png
      - assets/images/2.png
      - assets/images/3.png
      - assets/images/image.png
      - assets/images/image (1).png
      - assets/images/image (2).png
      - assets/images/belleza.jpeg
      - assets/images/streamming.jpeg
      - assets/images/interior.jpg



    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
  fonts:
      - family: WorkSansSemiBold
        fonts:
          - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

      - family: WorkSansBold
        fonts:
          - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

      - family: WorkSansMedium
        fonts:
          - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf



